export const ActionTypes = {
  /*   SET_PRODUCTS: "SET_PRODUCTS", */
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  GET_ORDERS: "GET_ORDERS",
  DELETE_ORDERS: "DELETE_ORDERS",
};
